{
  "name": "Model",
  "compatibilityLevel": 1567,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "guidance_raw",
        "lineageTag": "84f3d87d-c7e7-476a-a60f-1d5c05bfee8a",
        "columns": [
          {
            "name": "guidance_id",
            "dataType": "int64",
            "sourceColumn": "guidance_id",
            "lineageTag": "df78a52f-5b7d-4324-b5c6-1f79039acac8",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "transcript_id",
            "dataType": "int64",
            "sourceColumn": "transcript_id",
            "lineageTag": "3742a2b0-93d1-459f-be4c-69c6cfd11120",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "company_id",
            "dataType": "int64",
            "sourceColumn": "company_id",
            "lineageTag": "88a6257e-60b7-4b7e-ad0f-969e7d4ff50f",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "guidance_type",
            "dataType": "string",
            "sourceColumn": "guidance_type",
            "lineageTag": "047a0d4e-e88d-4ba4-b90e-07cd3cd4b56b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "stated_value",
            "dataType": "string",
            "sourceColumn": "stated_value",
            "lineageTag": "fb1ccaa1-8d1c-4d25-9b45-58ad29cb4bd8",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "direction",
            "dataType": "string",
            "sourceColumn": "direction",
            "lineageTag": "9633440f-f1d2-4d01-82b1-44ea36c19ab3",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "confidence",
            "dataType": "string",
            "sourceColumn": "confidence",
            "lineageTag": "6a6a65bd-9ba8-49ff-a9d3-e7eda9afdaab",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "source_excerpt",
            "dataType": "string",
            "sourceColumn": "source_excerpt",
            "lineageTag": "55fb86ca-9b42-4304-a2db-1fc0e807735b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "extracted_by",
            "dataType": "string",
            "sourceColumn": "extracted_by",
            "lineageTag": "34a93456-aa4b-4297-be3d-9550c2007887",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "created_at",
            "dataType": "string",
            "sourceColumn": "created_at",
            "lineageTag": "a5066898-b0e4-431b-b25b-d7d0f4c10a4c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ticker",
            "dataType": "string",
            "sourceColumn": "ticker",
            "lineageTag": "245fe837-0e53-4f07-9eb1-8086b59445a6",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "name",
            "dataType": "string",
            "sourceColumn": "name",
            "lineageTag": "9a860cbf-e03e-473c-a758-fbdc5da048a1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "quarter_label",
            "dataType": "string",
            "sourceColumn": "quarter_label",
            "lineageTag": "f281cc10-cb73-44e9-b865-e26e5628f93c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "guidance_raw",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\srija\\\\Downloads\\\\claude code\\\\projects\\\\earnings-guidance-reliability-tracker\\\\exports\\\\guidance_raw.csv\"),[Delimiter=\",\", Columns=13, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),\n    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),\n    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"guidance_id\", Int64.Type}, {\"transcript_id\", Int64.Type}, {\"company_id\", Int64.Type}, {\"guidance_type\", type text}, {\"stated_value\", type text}, {\"direction\", type text}, {\"confidence\", type text}, {\"source_excerpt\", type text}, {\"extracted_by\", type text}, {\"created_at\", type text}, {\"ticker\", type text}, {\"name\", type text}, {\"quarter_label\", type text}})\nin\n    #\"Changed Type\""
            }
          }
        ],
        "measures": [
          {
            "name": "Total Guidance Statements",
            "expression": "COUNTROWS(guidance_raw)",
            "lineageTag": "2b38f2c8-4221-4fe5-9ec6-4fe848a9c23b"
          },
          {
            "name": "High Confidence Statements",
            "expression": "CALCULATE(COUNTROWS(guidance_raw), guidance_raw[confidence] = \"high\")",
            "lineageTag": "1dd86c1e-b48c-4a08-b223-d8227a724308"
          },
          {
            "name": "Real vs Mock Extractions",
            "expression": "CALCULATE(COUNTROWS(guidance_raw), guidance_raw[extracted_by] = \"llm\")",
            "lineageTag": "d3e6580d-a8c4-4207-870a-f1cd441c129d"
          }
        ]
      },
      {
        "name": "guidance_vs_actuals",
        "lineageTag": "d0e5c202-2ccf-4e50-ad06-10a06d49ce39",
        "columns": [
          {
            "name": "ticker",
            "dataType": "string",
            "sourceColumn": "ticker",
            "lineageTag": "6460173f-0190-444a-b3f7-283ca7268c0a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "name",
            "dataType": "string",
            "sourceColumn": "name",
            "lineageTag": "42639dad-1618-4904-8242-62cc2bd05293",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "guidance_given_in_quarter",
            "dataType": "string",
            "sourceColumn": "guidance_given_in_quarter",
            "lineageTag": "6aa7b61d-2f3e-49ea-b68f-534ef7a7f18a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "guidance_call_date",
            "dataType": "string",
            "sourceColumn": "guidance_call_date",
            "lineageTag": "c4ae85da-dba2-46b3-a09a-fb3ab42b2c98",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "guidance_stated_value",
            "dataType": "string",
            "sourceColumn": "guidance_stated_value",
            "lineageTag": "f25983a1-4bbf-4441-96a4-05ef49dc9857",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "guidance_direction",
            "dataType": "string",
            "sourceColumn": "guidance_direction",
            "lineageTag": "a13c308f-8df9-4537-b73d-63888bb4f718",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "extraction_confidence",
            "dataType": "string",
            "sourceColumn": "extraction_confidence",
            "lineageTag": "adb9b5c0-fd23-4d99-9432-de25bfe0317e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "next_reported_period",
            "dataType": "string",
            "sourceColumn": "next_reported_period",
            "lineageTag": "008ff57e-12c7-4e11-9081-e3da1f477432",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "actual_revenue_qoq_growth_pct",
            "dataType": "double",
            "sourceColumn": "actual_revenue_qoq_growth_pct",
            "lineageTag": "c424064a-6b27-4bed-b5ae-207c51a619f3",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "source_excerpt",
            "dataType": "string",
            "sourceColumn": "source_excerpt",
            "lineageTag": "d3156b92-07ea-4b9d-a6b7-5319bba73dd8",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "guidance_vs_actuals",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\srija\\\\Downloads\\\\claude code\\\\projects\\\\earnings-guidance-reliability-tracker\\\\exports\\\\guidance_vs_actuals.csv\"),[Delimiter=\",\", Columns=10, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),\n    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),\n    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"ticker\", type text}, {\"name\", type text}, {\"guidance_given_in_quarter\", type text}, {\"guidance_call_date\", type text}, {\"guidance_stated_value\", type text}, {\"guidance_direction\", type text}, {\"extraction_confidence\", type text}, {\"next_reported_period\", type text}, {\"actual_revenue_qoq_growth_pct\", type number}, {\"source_excerpt\", type text}})\nin\n    #\"Changed Type\""
            }
          }
        ]
      }
    ],
    "relationships": [],
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"guidance_raw\", \"guidance_vs_actuals\"]"
      }
    ]
  }
}