{
  "name": "Model",
  "compatibilityLevel": 1567,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "guidance_raw",
        "lineageTag": "e57e1f96-e0a1-4f89-9733-76b34cd31029",
        "columns": [
          {
            "name": "guidance_id",
            "dataType": "int64",
            "sourceColumn": "guidance_id",
            "lineageTag": "42e995cb-105a-4b6c-a9d9-91de650e6f60",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "transcript_id",
            "dataType": "int64",
            "sourceColumn": "transcript_id",
            "lineageTag": "8b394a9a-98d3-4775-bc6e-c4bf0af0e18a",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "company_id",
            "dataType": "int64",
            "sourceColumn": "company_id",
            "lineageTag": "687f3b82-b63c-45be-8fae-8570d7c22e51",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "guidance_type",
            "dataType": "string",
            "sourceColumn": "guidance_type",
            "lineageTag": "89c48e17-42c6-4008-b51d-27ffa151ae17",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "stated_value",
            "dataType": "string",
            "sourceColumn": "stated_value",
            "lineageTag": "e04c0e72-ea26-4847-a9dd-090626acfc33",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "direction",
            "dataType": "string",
            "sourceColumn": "direction",
            "lineageTag": "0b789eb4-d78f-4731-aa43-5c667fe82cfd",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "confidence",
            "dataType": "string",
            "sourceColumn": "confidence",
            "lineageTag": "dbecde28-7ba6-40e6-9ce2-b9714a722d72",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "source_excerpt",
            "dataType": "string",
            "sourceColumn": "source_excerpt",
            "lineageTag": "f13e0d2d-eb95-40d4-a8f9-b91745a7995a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "extracted_by",
            "dataType": "string",
            "sourceColumn": "extracted_by",
            "lineageTag": "67472b16-6892-43e9-96fd-7830464d652b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "created_at",
            "dataType": "string",
            "sourceColumn": "created_at",
            "lineageTag": "a727e8a7-6f8e-4778-a590-f8e26ea55556",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ticker",
            "dataType": "string",
            "sourceColumn": "ticker",
            "lineageTag": "f279d340-fbe6-42b5-8503-d8b631cfb082",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "name",
            "dataType": "string",
            "sourceColumn": "name",
            "lineageTag": "233d3ab1-66dd-4d34-9362-706d6c8988c3",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "quarter_label",
            "dataType": "string",
            "sourceColumn": "quarter_label",
            "lineageTag": "8c62568e-77a1-4942-945d-727c1ec3ee50",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "guidance_raw",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\srija\\\\Downloads\\\\claude code\\\\projects\\\\earnings-guidance-reliability-tracker\\\\exports\\\\guidance_raw.csv\"),[Delimiter=\",\", Columns=13, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),\n    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),\n    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"guidance_id\", Int64.Type}, {\"transcript_id\", Int64.Type}, {\"company_id\", Int64.Type}, {\"guidance_type\", type text}, {\"stated_value\", type text}, {\"direction\", type text}, {\"confidence\", type text}, {\"source_excerpt\", type text}, {\"extracted_by\", type text}, {\"created_at\", type text}, {\"ticker\", type text}, {\"name\", type text}, {\"quarter_label\", type text}})\nin\n    #\"Changed Type\""
            }
          }
        ],
        "measures": [
          {
            "name": "Total Guidance Statements",
            "expression": "COUNTROWS(guidance_raw)",
            "lineageTag": "b989f23c-6cb5-49f0-886e-1aa19ac24855"
          },
          {
            "name": "High Confidence Statements",
            "expression": "CALCULATE(COUNTROWS(guidance_raw), guidance_raw[confidence] = \"high\")",
            "lineageTag": "554c8248-55f6-41f1-9c79-ac16fcfcfb08"
          },
          {
            "name": "Real vs Mock Extractions",
            "expression": "CALCULATE(COUNTROWS(guidance_raw), guidance_raw[extracted_by] = \"llm\")",
            "lineageTag": "e0de1239-bd3b-4dda-888a-3f9dd6b589cc"
          }
        ]
      },
      {
        "name": "guidance_vs_actuals",
        "lineageTag": "8ea09720-a3dc-49b0-9900-a3f670baec0f",
        "columns": [
          {
            "name": "ticker",
            "dataType": "string",
            "sourceColumn": "ticker",
            "lineageTag": "8045097c-5ce6-49f0-81c3-0c5a0937d6ce",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "name",
            "dataType": "string",
            "sourceColumn": "name",
            "lineageTag": "c3343cb1-2ef3-4a0a-a5c2-8a461789d46c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "guidance_given_in_quarter",
            "dataType": "string",
            "sourceColumn": "guidance_given_in_quarter",
            "lineageTag": "14f66a9b-43fe-4fab-89f7-bc589e45532d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "guidance_call_date",
            "dataType": "string",
            "sourceColumn": "guidance_call_date",
            "lineageTag": "96debac5-4818-4635-8240-c513eeab9f5d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "guidance_stated_value",
            "dataType": "string",
            "sourceColumn": "guidance_stated_value",
            "lineageTag": "e9229dbd-ebc4-44db-a05f-cd6bcce5dd54",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "guidance_direction",
            "dataType": "string",
            "sourceColumn": "guidance_direction",
            "lineageTag": "4ce499e3-2ca0-4c03-b240-12e89bc12718",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "extraction_confidence",
            "dataType": "string",
            "sourceColumn": "extraction_confidence",
            "lineageTag": "1dfc1ff0-f519-46b8-b47b-e600f471d5bd",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "next_reported_period",
            "dataType": "string",
            "sourceColumn": "next_reported_period",
            "lineageTag": "4df76d57-a8d8-40c4-b4c7-d5152b75e8f1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "actual_revenue_qoq_growth_pct",
            "dataType": "double",
            "sourceColumn": "actual_revenue_qoq_growth_pct",
            "lineageTag": "d18e9aaa-51a7-4f5a-a6d7-4de958d8977d",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "source_excerpt",
            "dataType": "string",
            "sourceColumn": "source_excerpt",
            "lineageTag": "01dea703-79c8-4ab7-a440-19312ea6da0c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "guidance_vs_actuals",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\srija\\\\Downloads\\\\claude code\\\\projects\\\\earnings-guidance-reliability-tracker\\\\exports\\\\guidance_vs_actuals.csv\"),[Delimiter=\",\", Columns=10, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),\n    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),\n    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"ticker\", type text}, {\"name\", type text}, {\"guidance_given_in_quarter\", type text}, {\"guidance_call_date\", type text}, {\"guidance_stated_value\", type text}, {\"guidance_direction\", type text}, {\"extraction_confidence\", type text}, {\"next_reported_period\", type text}, {\"actual_revenue_qoq_growth_pct\", type number}, {\"source_excerpt\", type text}})\nin\n    #\"Changed Type\""
            }
          }
        ]
      }
    ],
    "relationships": [],
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"guidance_raw\", \"guidance_vs_actuals\"]"
      }
    ]
  }
}